/*
# FleetVu V2.0 Roadmap — Core Schema Extension

## Purpose
Creates the database foundation for Part 2 of the V2.0 roadmap:
  1. Subscription request workflow (Items 12-14)
  2. POST check records (Item 3 / Feature 3 from Part 1)
  3. Sensor channel configuration for tripartite grille architecture (Item 2)
  4. Collision vs close-call event classification (Item 3)
  5. ZKP compliance certificates and incident packages (Item 6)
  6. Enterprise webhook configuration for TMS integration (Item 8)
  7. Driver onboarding flow state (Item 1)
  8. Feature gate extensions for EDGE pre-filtering, crypto-agility, ZKP, OpenAPI (Items 2, 5, 6, 8)

## New Tables

### subscription_requests
- Tracks subscription requests submitted by POC/Admin users.
- `id` (uuid PK)
- `company_id` (uuid, FK companies) — requesting fleet
- `company_name` (text) — denormalized
- `location` (text) — facility location
- `poc_name` (text) — point of contact
- `poc_email` (text) — POC email
- `affected_unit_count` (integer) — how many hardware units
- `hardware_serials` (text[]) — specific serial numbers affected
- `status` (text) — 'pending' | 'submitted' | 'invoiced' | 'paid' | 'active'
- `annual_total` (numeric) — calculated annual total
- `notes` (text)
- `created_at`, `updated_at` (timestamptz)

### post_check_records
- Records each Power-On Self-Test execution with results.
- `id` (uuid PK)
- `vehicle_id` (uuid, FK vehicles, nullable)
- `company_id` (uuid, FK companies, nullable)
- `hardware_serial` (text) — sensor hardware serial
- `sensors_checked` (integer)
- `passed` (boolean)
- `failures` (text[]) — list of failed channels
- `duration_ms` (integer)
- `triggered_by` (text) — 'auto_connect' | 'manual' | 'scheduled'
- `utc_timestamp` (timestamptz)
- `created_at` (timestamptz)

### sensor_channel_config
- Per-vehicle tripartite channel configuration for the 77GHz center grille radar.
- `id` (uuid PK)
- `vehicle_id` (uuid, FK vehicles, nullable)
- `company_id` (uuid, FK companies, nullable)
- `hardware_serial` (text)
- `channel_forward_range_m` (numeric, default 7.5)
- `channel_left_range_m` (numeric, default 2.0)
- `channel_right_range_m` (numeric, default 2.0)
- `edge_filter_enabled` (boolean, default false)
- `edge_filter_threshold_m` (numeric, default 5.0)
- `created_at`, `updated_at` (timestamptz)

### collision_events
- Classified collision vs close-call events from sensor+smartphone profiling.
- `id` (uuid PK)
- `vehicle_id` (uuid, FK vehicles, nullable)
- `driver_id` (uuid, FK drivers, nullable)
- `company_id` (uuid, FK companies, nullable)
- `event_type` (text) — 'proximity_near_miss' | 'verified_bumper_impact'
- `severity` (text) — 'low' | 'medium' | 'high' | 'critical'
- `channel_forward_reading` (numeric)
- `channel_left_reading` (numeric)
- `channel_right_reading` (numeric)
- `smartphone_jolt_g` (numeric) — smartphone motion sensor reading
- `impact_speed_mph` (numeric)
- `latitude` (numeric)
- `longitude` (numeric)
- `utc_timestamp` (timestamptz)
- `metadata` (jsonb)
- `created_at` (timestamptz)

### zkp_compliance_certificates
- ZKP-style compliance certificates generated by company admins.
- Uses Merkle proofs of inclusion — proves chain integrity without revealing raw data.
- `id` (uuid PK)
- `company_id` (uuid, FK companies)
- `generated_by` (text) — admin email
- `certificate_type` (text) — 'compliance' | 'incident_package'
- `chain_root_hash` (text) — Merkle root of the verified chain
- `block_range_start` (integer) — first block_seq in the certificate
- `block_range_end` (integer) — last block_seq
- `event_count` (integer) — total events covered
- `merkle_proof` (jsonb) — proof of inclusion data
- `metadata` (jsonb) — unmasked administrative metadata
- `status` (text) — 'generated' | 'exported' | 'revoked'
- `utc_timestamp` (timestamptz)
- `created_at` (timestamptz)

### enterprise_webhooks
- HMAC-SHA256 signed webhook endpoints for TMS integration.
- `id` (uuid PK)
- `company_id` (uuid, FK companies)
- `url` (text) — webhook endpoint URL
- `secret` (text) — HMAC signing secret
- `events` (text[]) — event types to subscribe to
- `is_active` (boolean, default true)
- `last_delivery_at` (timestamptz, nullable)
- `last_delivery_status` (text, nullable)
- `failure_count` (integer, default 0)
- `created_at`, `updated_at` (timestamptz)

### driver_onboarding_state
- Tracks the dual-path onboarding selection for new drivers.
- `id` (uuid PK)
- `driver_id` (uuid, FK drivers, nullable)
- `company_id` (uuid, FK companies, nullable)
- `driver_email` (text)
- `auth_method` (text) — 'biometric' | 'keycode' | 'pin_fallback'
- `webauthn_credential_id` (text, nullable) — registered credential ID
- `keycode_id` (uuid, nullable) — FK to driver_access_keycodes
- `pin_expires_at` (timestamptz, nullable) — 15-minute PIN fallback expiry
- `status` (text) — 'pending' | 'method_selected' | 'completed' | 'expired'
- `created_at`, `updated_at` (timestamptz)

## Modified Tables

### vault_feature_gates (ALTER)
- Added columns for V2 features:
  - `edge_pre_filtering_enabled` (boolean, default false)
  - `crypto_agility_enabled` (boolean, default false)
  - `zkp_compliance_enabled` (boolean, default false)
  - `openapi_webhooks_enabled` (boolean, default false)
  - `accident_reconstruction_enabled` (boolean, default false)

## Security
- RLS enabled on all new tables.
- Policies use `TO anon, authenticated` (consistent with existing FleetVu tables — single-tenant operational data).
- All tables follow the same 4-policy CRUD pattern (SELECT, INSERT, UPDATE, DELETE).
- zkp_compliance_certificates: SELECT + INSERT only (no UPDATE/DELETE — certificates are immutable once generated, like vault_event_blocks).
- enterprise_webhooks: full CRUD but the `secret` column should be handled carefully in client code.

## Important Notes
1. zkp_compliance_certificates is append-only (INSERT + SELECT) — certificates must never be modified after generation to preserve evidentiary integrity.
2. The `merkle_proof` column stores the proof structure as JSONB, containing sibling hashes and verification path.
3. sensor_channel_config has a per-vehicle config row — the EDGE pre-filtering logic reads from this table.
4. collision_events stores the classified result of the impact verification engine — raw sensor data stays in telemetry_events.
5. driver_onboarding_state tracks the welcome email → onboarding selection → completion flow.
6. enterprise_webhooks.secret is stored in plaintext for HMAC signing — in production this should be encrypted at rest, but for the current tier it's sufficient.
*/

-- ============================================================
-- subscription_requests: Subscription request workflow
-- ============================================================
CREATE TABLE IF NOT EXISTS subscription_requests (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id uuid REFERENCES companies(id) ON DELETE CASCADE,
  company_name text,
  location text,
  poc_name text,
  poc_email text,
  affected_unit_count integer DEFAULT 1,
  hardware_serials text[] DEFAULT '{}',
  status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'submitted', 'invoiced', 'paid', 'active')),
  annual_total numeric(10,2),
  notes text,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_subreq_company ON subscription_requests(company_id);
CREATE INDEX IF NOT EXISTS idx_subreq_status ON subscription_requests(status);

ALTER TABLE subscription_requests ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "anon_select_subreq" ON subscription_requests;
CREATE POLICY "anon_select_subreq" ON subscription_requests FOR SELECT
  TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "anon_insert_subreq" ON subscription_requests;
CREATE POLICY "anon_insert_subreq" ON subscription_requests FOR INSERT
  TO anon, authenticated WITH CHECK (true);

DROP POLICY IF EXISTS "anon_update_subreq" ON subscription_requests;
CREATE POLICY "anon_update_subreq" ON subscription_requests FOR UPDATE
  TO anon, authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "anon_delete_subreq" ON subscription_requests;
CREATE POLICY "anon_delete_subreq" ON subscription_requests FOR DELETE
  TO anon, authenticated USING (true);

-- ============================================================
-- post_check_records: Power-On Self-Test execution log
-- ============================================================
CREATE TABLE IF NOT EXISTS post_check_records (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  vehicle_id uuid REFERENCES vehicles(id) ON DELETE SET NULL,
  company_id uuid REFERENCES companies(id) ON DELETE SET NULL,
  hardware_serial text,
  sensors_checked integer NOT NULL DEFAULT 0,
  passed boolean NOT NULL DEFAULT false,
  failures text[] DEFAULT '{}',
  duration_ms integer DEFAULT 0,
  triggered_by text DEFAULT 'manual',
  utc_timestamp timestamptz DEFAULT now(),
  created_at timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_postcheck_vehicle ON post_check_records(vehicle_id);
CREATE INDEX IF NOT EXISTS idx_postcheck_company ON post_check_records(company_id);
CREATE INDEX IF NOT EXISTS idx_postcheck_timestamp ON post_check_records(utc_timestamp);

ALTER TABLE post_check_records ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "anon_select_postcheck" ON post_check_records;
CREATE POLICY "anon_select_postcheck" ON post_check_records FOR SELECT
  TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "anon_insert_postcheck" ON post_check_records;
CREATE POLICY "anon_insert_postcheck" ON post_check_records FOR INSERT
  TO anon, authenticated WITH CHECK (true);

DROP POLICY IF EXISTS "anon_update_postcheck" ON post_check_records;
CREATE POLICY "anon_update_postcheck" ON post_check_records FOR UPDATE
  TO anon, authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "anon_delete_postcheck" ON post_check_records;
CREATE POLICY "anon_delete_postcheck" ON post_check_records FOR DELETE
  TO anon, authenticated USING (true);

-- ============================================================
-- sensor_channel_config: Tripartite grille channel configuration
-- ============================================================
CREATE TABLE IF NOT EXISTS sensor_channel_config (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  vehicle_id uuid REFERENCES vehicles(id) ON DELETE CASCADE,
  company_id uuid REFERENCES companies(id) ON DELETE CASCADE,
  hardware_serial text,
  channel_forward_range_m numeric(4,1) NOT NULL DEFAULT 7.5,
  channel_left_range_m numeric(4,1) NOT NULL DEFAULT 2.0,
  channel_right_range_m numeric(4,1) NOT NULL DEFAULT 2.0,
  edge_filter_enabled boolean NOT NULL DEFAULT false,
  edge_filter_threshold_m numeric(4,1) NOT NULL DEFAULT 5.0,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_sensorcfg_vehicle ON sensor_channel_config(vehicle_id);
CREATE INDEX IF NOT EXISTS idx_sensorcfg_company ON sensor_channel_config(company_id);

ALTER TABLE sensor_channel_config ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "anon_select_sensorcfg" ON sensor_channel_config;
CREATE POLICY "anon_select_sensorcfg" ON sensor_channel_config FOR SELECT
  TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "anon_insert_sensorcfg" ON sensor_channel_config;
CREATE POLICY "anon_insert_sensorcfg" ON sensor_channel_config FOR INSERT
  TO anon, authenticated WITH CHECK (true);

DROP POLICY IF EXISTS "anon_update_sensorcfg" ON sensor_channel_config;
CREATE POLICY "anon_update_sensorcfg" ON sensor_channel_config FOR UPDATE
  TO anon, authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "anon_delete_sensorcfg" ON sensor_channel_config;
CREATE POLICY "anon_delete_sensorcfg" ON sensor_channel_config FOR DELETE
  TO anon, authenticated USING (true);

-- ============================================================
-- collision_events: Classified collision vs close-call events
-- ============================================================
CREATE TABLE IF NOT EXISTS collision_events (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  vehicle_id uuid REFERENCES vehicles(id) ON DELETE SET NULL,
  driver_id uuid REFERENCES drivers(id) ON DELETE SET NULL,
  company_id uuid REFERENCES companies(id) ON DELETE SET NULL,
  event_type text NOT NULL CHECK (event_type IN ('proximity_near_miss', 'verified_bumper_impact')),
  severity text NOT NULL DEFAULT 'low' CHECK (severity IN ('low', 'medium', 'high', 'critical')),
  channel_forward_reading numeric(6,2),
  channel_left_reading numeric(6,2),
  channel_right_reading numeric(6,2),
  smartphone_jolt_g numeric(6,3),
  impact_speed_mph numeric(6,2),
  latitude numeric(10,6),
  longitude numeric(10,6),
  utc_timestamp timestamptz DEFAULT now(),
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_collision_vehicle ON collision_events(vehicle_id);
CREATE INDEX IF NOT EXISTS idx_collision_company ON collision_events(company_id);
CREATE INDEX IF NOT EXISTS idx_collision_type ON collision_events(event_type);
CREATE INDEX IF NOT EXISTS idx_collision_timestamp ON collision_events(utc_timestamp);

ALTER TABLE collision_events ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "anon_select_collision" ON collision_events;
CREATE POLICY "anon_select_collision" ON collision_events FOR SELECT
  TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "anon_insert_collision" ON collision_events;
CREATE POLICY "anon_insert_collision" ON collision_events FOR INSERT
  TO anon, authenticated WITH CHECK (true);

DROP POLICY IF EXISTS "anon_update_collision" ON collision_events;
CREATE POLICY "anon_update_collision" ON collision_events FOR UPDATE
  TO anon, authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "anon_delete_collision" ON collision_events;
CREATE POLICY "anon_delete_collision" ON collision_events FOR DELETE
  TO anon, authenticated USING (true);

-- ============================================================
-- zkp_compliance_certificates: ZKP-style compliance reporting (append-only)
-- ============================================================
CREATE TABLE IF NOT EXISTS zkp_compliance_certificates (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id uuid REFERENCES companies(id) ON DELETE CASCADE,
  generated_by text,
  certificate_type text NOT NULL DEFAULT 'compliance' CHECK (certificate_type IN ('compliance', 'incident_package')),
  chain_root_hash text NOT NULL,
  block_range_start integer NOT NULL,
  block_range_end integer NOT NULL,
  event_count integer NOT NULL DEFAULT 0,
  merkle_proof jsonb NOT NULL DEFAULT '{}'::jsonb,
  metadata jsonb DEFAULT '{}'::jsonb,
  status text NOT NULL DEFAULT 'generated' CHECK (status IN ('generated', 'exported', 'revoked')),
  utc_timestamp timestamptz DEFAULT now(),
  created_at timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_zkp_company ON zkp_compliance_certificates(company_id);
CREATE INDEX IF NOT EXISTS idx_zkp_type ON zkp_compliance_certificates(certificate_type);
CREATE INDEX IF NOT EXISTS idx_zkp_status ON zkp_compliance_certificates(status);

ALTER TABLE zkp_compliance_certificates ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "anon_select_zkp" ON zkp_compliance_certificates;
CREATE POLICY "anon_select_zkp" ON zkp_compliance_certificates FOR SELECT
  TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "anon_insert_zkp" ON zkp_compliance_certificates;
CREATE POLICY "anon_insert_zkp" ON zkp_compliance_certificates FOR INSERT
  TO anon, authenticated WITH CHECK (true);

-- No UPDATE or DELETE — certificates are immutable once generated

-- ============================================================
-- enterprise_webhooks: HMAC-SHA256 signed webhook endpoints
-- ============================================================
CREATE TABLE IF NOT EXISTS enterprise_webhooks (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id uuid REFERENCES companies(id) ON DELETE CASCADE,
  url text NOT NULL,
  secret text NOT NULL,
  events text[] NOT NULL DEFAULT '{}'::text[],
  is_active boolean NOT NULL DEFAULT true,
  last_delivery_at timestamptz,
  last_delivery_status text,
  failure_count integer NOT NULL DEFAULT 0,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_webhooks_company ON enterprise_webhooks(company_id);
CREATE INDEX IF NOT EXISTS idx_webhooks_active ON enterprise_webhooks(is_active);

ALTER TABLE enterprise_webhooks ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "anon_select_webhooks" ON enterprise_webhooks;
CREATE POLICY "anon_select_webhooks" ON enterprise_webhooks FOR SELECT
  TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "anon_insert_webhooks" ON enterprise_webhooks;
CREATE POLICY "anon_insert_webhooks" ON enterprise_webhooks FOR INSERT
  TO anon, authenticated WITH CHECK (true);

DROP POLICY IF EXISTS "anon_update_webhooks" ON enterprise_webhooks;
CREATE POLICY "anon_update_webhooks" ON enterprise_webhooks FOR UPDATE
  TO anon, authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "anon_delete_webhooks" ON enterprise_webhooks;
CREATE POLICY "anon_delete_webhooks" ON enterprise_webhooks FOR DELETE
  TO anon, authenticated USING (true);

-- ============================================================
-- driver_onboarding_state: Dual-path onboarding flow
-- ============================================================
CREATE TABLE IF NOT EXISTS driver_onboarding_state (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  driver_id uuid REFERENCES drivers(id) ON DELETE CASCADE,
  company_id uuid REFERENCES companies(id) ON DELETE CASCADE,
  driver_email text NOT NULL,
  auth_method text CHECK (auth_method IN ('biometric', 'keycode', 'pin_fallback')),
  webauthn_credential_id text,
  keycode_id uuid REFERENCES driver_access_keycodes(id) ON DELETE SET NULL,
  pin_expires_at timestamptz,
  status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'method_selected', 'completed', 'expired')),
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_onboarding_driver ON driver_onboarding_state(driver_id);
CREATE INDEX IF NOT EXISTS idx_onboarding_company ON driver_onboarding_state(company_id);
CREATE INDEX IF NOT EXISTS idx_onboarding_email ON driver_onboarding_state(driver_email);
CREATE INDEX IF NOT EXISTS idx_onboarding_status ON driver_onboarding_state(status);

ALTER TABLE driver_onboarding_state ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "anon_select_onboarding" ON driver_onboarding_state;
CREATE POLICY "anon_select_onboarding" ON driver_onboarding_state FOR SELECT
  TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "anon_insert_onboarding" ON driver_onboarding_state;
CREATE POLICY "anon_insert_onboarding" ON driver_onboarding_state FOR INSERT
  TO anon, authenticated WITH CHECK (true);

DROP POLICY IF EXISTS "anon_update_onboarding" ON driver_onboarding_state;
CREATE POLICY "anon_update_onboarding" ON driver_onboarding_state FOR UPDATE
  TO anon, authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "anon_delete_onboarding" ON driver_onboarding_state;
CREATE POLICY "anon_delete_onboarding" ON driver_onboarding_state FOR DELETE
  TO anon, authenticated USING (true);

-- ============================================================
-- ALTER vault_feature_gates: Add V2 feature columns
-- ============================================================
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns
    WHERE table_name = 'vault_feature_gates' AND column_name = 'edge_pre_filtering_enabled') THEN
    ALTER TABLE vault_feature_gates ADD COLUMN edge_pre_filtering_enabled boolean NOT NULL DEFAULT false;
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns
    WHERE table_name = 'vault_feature_gates' AND column_name = 'crypto_agility_enabled') THEN
    ALTER TABLE vault_feature_gates ADD COLUMN crypto_agility_enabled boolean NOT NULL DEFAULT false;
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns
    WHERE table_name = 'vault_feature_gates' AND column_name = 'zkp_compliance_enabled') THEN
    ALTER TABLE vault_feature_gates ADD COLUMN zkp_compliance_enabled boolean NOT NULL DEFAULT false;
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns
    WHERE table_name = 'vault_feature_gates' AND column_name = 'openapi_webhooks_enabled') THEN
    ALTER TABLE vault_feature_gates ADD COLUMN openapi_webhooks_enabled boolean NOT NULL DEFAULT false;
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns
    WHERE table_name = 'vault_feature_gates' AND column_name = 'accident_reconstruction_enabled') THEN
    ALTER TABLE vault_feature_gates ADD COLUMN accident_reconstruction_enabled boolean NOT NULL DEFAULT false;
  END IF;
END $$;
